# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ángel Alarcón Site
    url: https://www.angelalarcon.com/es/
  - name: Ángel Alarcón Blog
    url: https://www.angelalarcon.com/marca/

assignees: # Users to assign downtime issues (optional)
  - david8z

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ag-uptime
  name: Ángel Alarcón Uptime
  introTitle: "Uptime checks for [**Ángel Alarcón**](https://www.angelalarcon.com/es/)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
